services:
####### MARIADB ########
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - inteption_net
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

####### WORDPRESS ########
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    volumes:
      - wp:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - inteption_net
    expose:
      - "9000"
    restart: on-failure
    healthcheck:
      test: ["CMD", "cgi-fcgi", "-bind", "-connect", "localhost:9000"]
      interval: 10s
      timeout: 40s
      retries: 5
      start_period: 30s

####### NGINX ########
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
    networks:
      - inteption_net
    depends_on:
      wordpress:
        condition: service_healthy
    restart: on-failure

####### REDIS ########
  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    image: redis
    depends_on:
      - wordpress
    networks:
      - inteption_net
    restart: always
    ports:
     - '6379:6379'
    env_file:
      - .env
    command:
      - --appendonly
      - "yes"
      - --requirepass
      - "${REDIS_PASSWORD}"
    volumes:
      - "wp:/var/www/html"

####### ADMINER ########
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - mariadb
    expose:
     - "9000"
    networks:
      - inteption_net

####### CADVISOR ########
  cadvisor:
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    image: cadvisor
    ports:
       - "8080:8080"
    networks:
     - inteption_net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw              # docker.sock
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro  # cgroups v2
    restart: always

####### VOLUMES ########
volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: 'none'
      o: "bind"
      device: ${HOME}/data/mysql
  wp:
    name: wp
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/wordpress

####### NETWORKS ########
networks:
    inteption_net:
        driver: bridge